name: Deploy to O2Switch

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
        npm run build

    - name: Deploy to O2Switch via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}  
        username: ${{ secrets.FTP_USERNAME }} 
        password: ${{ secrets.FTP_PASSWORD }} 
        local-dir: dist/  
        server-dir: sites/wikibook.adrienaubourg.fr 
